server:
  port: 9528
spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/chemicalsystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
# 集成mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmkjspringboot.chemicalsystem.entity

#配置外部访问文件
cbs-excelsPath: file:/C:/ExcelTemplates/
